# Site settings
title: Mahaputera
name: Mahaputera.art
description: kata kita kata kata
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mahaputera.art" # the base hostname & protocol for your site e.g. https://materializeblog.com
google_analytics: "UA-155101955-3"

# User settings
profile_img_url: https://materializecss.com/res/materialize.svg
username: mahaputera
user_description: Creative and Ambitious Computer Geek.
email: ardhwood@gmail.com
github_username: taufardh
fb_username: taufardh
twitter_username: taufardh
instagram_username: taufardh
linkedin_username: taufardh
disqus_username: taufardh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 2

#gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Plugins
plugins:
  - jemoji

# sass
sass:
  sass_dir: '_sass'
  style: compressed

#links
links:
  - title: Home
    url: "/"
    icon: dashboard
  - title: Blog
    url: /blog
    icon: article
  - title: Archive
    url: /archive
    icon: event
  - title: Painting
    url: "https://painting.mahaputera.art"
    icon: palette
    external: true
  - title: Photo
    url: "https://photo.mahaputera.art"
    icon: camera-alt
    external: true
  - title: Market
    url: "https://market.mahaputera.art"
    icon: local-mall
    external: true
